// <auto-generated />
namespace MyShop.Data.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedCustomersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCustomersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109130122323_addedCustomersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
